# fly.toml app configuration file generated for tg-event-bot-delicate-meadow-3842 on 2025-08-29T02:25:52+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tg-event-bot'
primary_region = 'waw'

[build]
  builder = 'paketobuildpacks/builder:base'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
