# fly.toml app configuration file generated for tg-event-bot-delicate-meadow-3842 on 2025-08-29T02:25:52+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tg-event-bot-delicate-meadow-3842'
primary_region = 'waw'

[build]
  builder = 'paketobuildpacks/builder:base'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
